[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bl100_hat"
authors = [
  {name="SunFounder", email="service@sunfounder.com" },
]
description = "BL100 Hat Python library for Raspberry Pi"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
]
keywords = ["bl100_hat", "sunfounder"]
dynamic = ["version"]

dependencies = [

]

[project.scripts]
bl100_hat = "bl100_hat:__main__"

[project.urls]
Homepage = ""
Documentation = ""
Repository = ""
Issues = ""
Changelog = ""

[tool.setuptools.packages.find]
include = ["bl100_hat"]
exclude = ["setup.py", "docs", 'tests*', 'examples', 'workspace']

[tool.setuptools.dynamic]
version = {attr = "bl100_hat.__version__"}


